insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (1, 'jbond007@yahoo.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher1', 'RO, EN', 'James', 'Bond', 'Available', '0722250000', 'CE');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (2, 'ricky_gerv@yahoo.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher2', 'RO, DE', 'Ricky', 'Gervais', 'Available', '0733758000', 'C');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (14, 'john.doe@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher3', 'RO', 'John', 'Doe', 'Available', '0722134000', 'BE');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (4, 'chuckNorris1@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher4', 'RO, ES', 'Chuck', 'Norris', 'Available', '0722268900', 'C');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (5, 'brad.pitt34@yahoo.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher5', 'RO', 'Brad', 'Pitt', 'Holiday', '0722268900', 'D');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (6, 'tom.cruise@yahoo.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher6', 'RO', 'Tom', 'Cruise', 'Holiday', '0722230000', 'D');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (8, 'chapelle123@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher7', 'RO', 'Dave', 'Chapelle', 'Medical', '0722334000', 'C1E');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (12, 'billburr33@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher8', 'RO, IT', 'Bill', 'Burr', 'Medical', '0726670000', 'D');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (13, 'joe.rogan9@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DISPATCHER', 'dispatcher9', 'RO', 'Joe', 'Rogan', 'Former', '0722250000', 'C');

insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (50, 'mario@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver1', 'RO, EN', 'Mario', 'Andretti', 'Available', '0722250000', 'B1, B');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (3, 'schumacher@yahoo.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver2', 'RO, DE','Michael', 'Schumacher','Available', '0733758000', 'B, B1');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (9, 'earnhardt8@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver3', 'RO', 'Dale', 'Earnhardt', 'Medical', '0722134000', 'D1E');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (10, 'hamilton@yahoo.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver4', 'RO, EN', 'Lewis', 'Hamilton', 'OnRoute', '0722268900', 'B1, BE');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (11, 'cturonea@yahoo.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver5', 'RO', 'Sebastian', 'Vettel', 'DayOff', '0722230000', 'B1');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (47, 'clarkson@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver6', 'RO, EN', 'Jeremy', 'Clarkson', 'Available', '0722334000', 'BE');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (48, 'hammond@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver7', 'RO', 'Richard', 'Hammond', 'Holiday', '0726670000', 'B1');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (42, 'james-may@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver8', 'RO', 'James', 'May', 'Former', '0722250000', 'B');
insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (43, 'ahinsch16@gmail.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'DRIVER', 'driver9', 'RO', 'Adrian', 'Hinsch', 'OnRoute', '0722250000', 'BE');

insert into USERS (id, email, password, role, username, spoken_language, first_name, last_name, user_status, phone_number, driving_license_category) values (25, 'admin@admin.com', '$2a$10$u1CcYPi1OFlZTMx2it7ED.w5sDeezEkMUNlvg8gDaL9rYLIVN0RI2', 'ADMIN', 'admin', 'ES', 'Ajay', 'Sweating', 'Available', '8084724623', 'CE');
