insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (1, 'CM8261', 'Electric', '2021-03-01', false, true, '2021-03-01', 'Tesla M X', 4, 'Pellentesque eget nunc.', 'TM 01 NFS', '2021-03-01', '2021-03-01', 'Available');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (2, 'CM8262', 'Electric', '2021-03-01', true, true, '2021-03-01', 'Tesla M Y', 4, 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'TM 02 NFS', '2021-03-01', '2021-03-01', 'Available');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (3, 'CM8263', 'Gasoline', '2021-03-01', true, true, '2021-03-01', 'Dacia Logan', 4, 'Suspendisse potenti.', 'TM 03 NFS', '2021-03-01', '2021-03-01', 'Available');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (4, 'CM8264', 'Diesel', '2021-03-01', true, false, '2021-03-01', 'Dacia Lodgy', 8, 'Nulla nisl.', 'TM 04 NFS', '2021-03-01', '2021-03-01', 'Available');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (5, 'CM8265', 'Gasoline', '2021-03-01', true, false, '2021-03-01', 'Dacia Lodgy', 8, 'Integer tincidunt ante vel ipsum.', 'TM 05 NFS', '2021-03-01', '2021-03-01', 'OnRoute');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (6, 'CM8266', 'Diesel', '2021-03-01', true, true, '2021-03-01', 'Ferrari Spider', 2, 'Proin eu mi.', 'TM 06 NFS', '2021-03-01', '2021-03-01', 'OnRoute');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (7, 'CM8267', 'Diesel', '2021-03-01', true, false, '2021-03-01', 'Lamborghini Aventador', 2, 'Nam dui.', 'TM 07 NFS', '2021-03-01', '2021-03-01', 'OnRoute');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (8, 'CM8268', 'Gasoline', '2021-03-01', false, true, '2021-03-01', 'Dacia Duster', 4, 'Nulla ut erat id mauris vulputate elementum.', 'TM 08 NFS', '2021-03-01', '2021-03-01', 'Defective');
insert into CARS (id, chassis_number, engine_type, huvignette_expiration_date, is_in_transit, is_rented, itp_expiration_date, model, number_of_seats, others, plate_number, rca_expiration_date, rovignette_expiration_date, status) values (9, 'CM8269', 'Gasoline', '2021-03-01', false, true, '2021-03-01', 'Dacia Duster', 4, 'Morbi quis tortor id nulla ultrices aliquet.', 'TM 09 NFS', '2021-03-01', '2021-03-01', 'Defective');
