INSERT INTO transfers (id, car_id, driver_id, route_id) VALUES (1, 2, 47, 5);
INSERT INTO transfers (id, car_id, driver_id, route_id) VALUES (2, 3, 47, 4);
INSERT INTO transfers (id, car_id, driver_id, route_id) VALUES (3, 3, 3, 3);
INSERT INTO transfers (id, car_id, driver_id, route_id) VALUES (4, 5, 3, 4);
INSERT INTO transfers (id, car_id, driver_id, route_id) VALUES (5, 2, 50, 3);
INSERT INTO transfers (id, car_id, driver_id, route_id) VALUES (6, 3, 3, 2);

insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status) values (1, 'Winny', 'Pigne', 'wpigne0@home.pl', 2, 1, 1, 'Strada Mihai Eminescu 2 Arad', '2020-09-15T13:10:14', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 'Online', '0722250000', 'Calea Sever Bocu 50 Timisoara', '2020-09-15T13:10:14', 'Strada Mihai Eminescu 2, Arad', 'In hac habitasse platea dictumst.', '0 Fisk Point', '2020-09-15T13:10:14', 1, 'Private', 5, 'NotAssigned');
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status) values (2, 'Alexandra', 'Mostin', 'amostin1@foxnews.com', 2, 1, 1, 'Gheorghe Lazar 3 Timisoara', '2020-09-15T13:10:14', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 0, 'Cash', '0733758000', 'Vasile Goldiș 1 Arad', '2020-09-15T13:10:14', '96 Raven Drive', 'Integer tincidunt ante vel ipsum.', '32 Chive Park', '2020-09-15T13:10:14', 1, 'Shuttle', 6, 'NotAssigned');
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status,transfer_id) values (3, 'Margaretta', 'Guiver', 'mguiver2@samsung.com', 1, 1, 2, 'Bulevar kralja Aleksandra 94 Belgrad', '2020-06-30T16:20:14', 'Nam dui.', 1, 'Online', '0722134000', 'Gheorghe Bariţiu 27 Arad', '2020-09-15T13:10:14', '16 Kinsman Trail', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '8 Merchant Plaza', '2020-06-30T15:20:14', 1, 'Shuttle', 3, 'OnRoute',3);
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status,transfer_id) values (4, 'Saw', 'O''Roan', 'soroan3@cloudflare.com', 2, 2, 1, 'Emanoil Gojdu 17 Arad', '2020-06-30T13:10:14', 'Aliquam quis turpis eget elit sodales scelerisque.', 1, 'Online', '0722268900', 'Bulevar kralja Aleksandra 90 Belgrad', '2020-09-15T13:10:14', '5 Sherman Crossing', 'Quisque ut erat.', '5 Orin Drive', '2020-06-30T13:10:14', 0, 'Private', 4, 'OnRoute',4);
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status,transfer_id) values (5, 'Marty', 'Rutgers', 'mrutgers4@canalblog.com', 2, 0, 0, 'Bulevar kralja Aleksandra 90 Belgrad', '2020-09-15T13:10:14', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 1, 'Online', '0722268900', 'Vasile Goldiș 4 Arad', '2020-06-30T15:20:14', '757 Onsgard Junction', 'Etiam pretium iaculis justo.', '686 Shopko Road', '2020-09-15T13:10:14', 1, 'Private', 3, 'Assigned',5);
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status,transfer_id) values (6, 'Hurleigh', 'Messier', 'hmessier5@geocities.com', 1, 0, 0, 'Strada Torontalului 1 Timisoara', '2020-09-15T13:10:14', 'Suspendisse ornare consequat lectus.', 1, 'Cash', '0722230000', 'Dunabogdány Bogonháti 8 Ungaria', '2020-06-30T13:10:14', '3453 Luster Parkway', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '446 Golf Course Lane', '2020-09-15T13:10:14', 0, 'Shuttle', 2, 'Assigned',6);
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status,transfer_id) values (7, 'Millie', 'Varley', 'mvarley6@cnbc.com', 2, 0, 0, 'Strada George Coșbuc 23 Arad', '2020-09-15T13:10:14', 'Pellentesque eget nunc.', 1, 'Cash', '0722334000', 'Popa Laurentiu 2 Timisoara', '2020-03-20T15:10:14', '5608 Havey Way', 'Aliquam sit amet diam in magna bibendum imperdiet.', '9 Helena Point', '2020-09-15T13:10:14', 1, 'Private', 5, 'TransferDone',1);
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status,transfer_id) values (8, 'Julissa', 'Lowres', 'jlowres7@artisteer.com', 1, 2, 0, 'Strada Trandafirilor 11 Arad', '2020-09-15T13:10:14', 'Integer ac leo.', 1, 'Cash', '0726670000', 'Bulevar kralja Aleksandra 88 Belgrad', '2020-04-15T13:15:22', '68 Eagan Road', 'In blandit ultrices enim.', '925 Westerfield Terrace', '2020-09-15T13:10:14', 1, 'Shuttle', 4, 'TransferDone',2);
insert into PASSENGERS (id, first_name, last_name, email, number_of_adults, number_of_children, number_of_infants, destination_address, flight_date_time, flight_details, paid_for_transfer, payment_method, phone_number, pick_up_address, pick_up_date_time, return_destination_address, return_flight_details, return_pick_up_address, return_pick_up_date_time, return_transfer, transport_type, route_id, status) values (9, 'Rikki', 'McDuffie', 'rmcduffie8@walmart.com', 6, 0, 0, 'Strada Torontalului 5 Timisoara', '2020-09-15T13:10:14', 'Integer ac neque.', 0, 'Cash', '0722250000', 'Dunabogdány Bogonháti 6 Ungaria', '2020-09-15T13:10:14', '75222 Little Fleur Pass', 'Nullam varius.', '977 Blaine Place', '2020-09-15T13:10:14', 1, 'Shuttle', 2, 'Canceled');
